objects = \
	attr_constant.hpp.gch\
	attr_tuple.hpp.gch\
	attr_enumerate.hpp.gch\
	attr_color.hpp.gch\
	attr_anything.hpp.gch\
	attr_integer.hpp.gch\
	attr_list-of-numbers.hpp.gch\
	attr_URL.hpp.gch\
	attr_transform-list.hpp.gch\
	attr_percentage.hpp.gch\
	attr_length.hpp.gch\
	attr_IRI.hpp.gch\
	attr_paint.hpp.gch\
	attr_name.hpp.gch\
	attr_angle.hpp.gch\
	attr_opacity-value.hpp.gch\
	attr_number.hpp.gch\
	attr_FuncIRI.hpp.gch
cc = g++

.PHONY: all
all: $(objects)

attr_color.hpp.gch: attr_color.hpp
	$(cc) -c attr_color.hpp
attr_anything.hpp.gch: attr_anything.hpp
	$(cc) -c attr_anything.hpp
attr_integer.hpp.gch: attr_integer.hpp
	$(cc) -c attr_integer.hpp
attr_list-of-numbers.hpp.gch: attr_list-of-numbers.hpp
	$(cc) -c attr_list-of-numbers.hpp
attr_URL.hpp.gch: attr_URL.hpp
	$(cc) -c attr_URL.hpp
attr_transform-list.hpp.gch: attr_transform-list.hpp
	$(cc) -c attr_transform-list.hpp
attr_percentage.hpp.gch: attr_percentage.hpp
	$(cc) -c attr_percentage.hpp
attr_length.hpp.gch: attr_length.hpp
	$(cc) -c attr_length.hpp
attr_IRI.hpp.gch: attr_IRI.hpp
	$(cc) -c attr_IRI.hpp
attr_paint.hpp.gch: attr_paint.hpp
	$(cc) -c attr_paint.hpp
attr_name.hpp.gch: attr_name.hpp
	$(cc) -c attr_name.hpp
attr_angle.hpp.gch: attr_angle.hpp
	$(cc) -c attr_angle.hpp
attr_opacity-value.hpp.gch: attr_opacity-value.hpp
	$(cc) -c attr_opacity-value.hpp
attr_number.hpp.gch: attr_number.hpp
	$(cc) -c attr_number.hpp
attr_FuncIRI.hpp.gch: attr_FuncIRI.hpp
	$(cc) -c attr_FuncIRI.hpp
attr_constant.hpp.gch: attr_constant.hpp
	$(cc) -c attr_constant.hpp
attr_tuple.hpp.gch: attr_tuple.hpp
	$(cc) -c attr_tuple.hpp
attr_enumerate.hpp.gch: attr_enumerate.hpp
	$(cc) -c attr_enumerate.hpp

.PHONY: all
clean:
	-rm $(objects)
